name: Docker Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mayanksuryawanshi1/vocab-vista:latest .

      - name: Push Docker image
        run: docker push mayanksuryawanshi1/vocab-vista:latest

      - name: Deploy to Render
        uses: render-examples/deploy-render@v1
        with:
          api_key: ${{ secrets.RENDER_API_KEY }}
          service_id: srv-d38sdiogjchc73daancg
